# Generated by Django 5.2.6 on 2025-09-22 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TickerHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=20)),
                ("interval", models.CharField(default="1d", max_length=10)),
                ("timestamp", models.DateTimeField()),
                ("open_price", models.FloatField(blank=True, null=True)),
                ("high_price", models.FloatField(blank=True, null=True)),
                ("low_price", models.FloatField(blank=True, null=True)),
                ("close_price", models.FloatField(blank=True, null=True)),
                ("volume", models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["symbol", "timestamp"],
                        name="market_tick_symbol_ec269b_idx",
                    )
                ],
                "unique_together": {("symbol", "timestamp", "interval")},
            },
        ),
    ]
