# Generated by Django 5.2.6 on 2025-09-27 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0002_tickerhistory"),
    ]

    operations = [
        migrations.CreateModel(
            name="Markets",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
